---@param theme evergarden.types.theme
---@param config evergarden.types.config
return function(theme, config)
  return {
    ['@annotation']            = { link = "TSAnnotation" },
    ['@attribute']             = { link = "TSAttribute" },
    ['@boolean']               = { link = "TSBoolean" },
    ['@character']             = { link = "TSCharacter" },
    ['@comment']               = { link = "TSComment" },
    ['@conditional']           = { link = "TSConditional" },
    ['@constant']              = { link = "TSConstant" },
    ['@constant.builtin']      = { link = "TSConstBuiltin" },
    ['@constant.macro']        = { link = "TSConstMacro" },
    ['@constructor']           = { link = "TSConstructor" },
    ['@exception']             = { link = "TSException" },
    ['@field']                 = { link = "TSField" },
    ['@float']                 = { link = "TSFloat" },
    ['@function']              = { link = "TSFunction" },
    ['@function.call']         = { link = "TSFunction" },
    ['@function.builtin']      = { link = "TSFuncBuiltin" },
    ['@function.macro']        = { link = "TSFuncMacro" },
    ['@include']               = { link = "TSInclude" },
    ['@keyword']               = { link = "TSKeyword" },
    ['@keyword.function']      = { link = "TSKeywordFunction" },
    ['@keyword.operator']      = { link = "TSKeywordOperator" },
    ['@label']                 = { link = "TSLabel" },
    ['@method']                = { link = "TSMethod" },
    ['@method.call']           = { link = "@function.call" },
    ['@namespace']             = { link = "TSNamespace" },
    ['@none']                  = { link = "TSNone" },
    ['@number']                = { link = "TSNumber" },
    ['@operator']              = { link = "TSOperator" },
    ['@parameter']             = { link = "TSParameter" },
    ['@parameter.reference']   = { link = "TSParameterReference" },
    ['@property']              = { link = "TSProperty" },
    ['@punctuation.bracket']   = { link = "TSPunctBracket" },
    ['@punctuation.delimiter'] = { link = "TSPunctDelimiter" },
    ['@punctuation.special']   = { link = "TSPunctSpecial" },
    ['@repeat']                = { link = "TSRepeat" },
    ['@storageclass']          = { link = "TSStorageClass" },
    ['@string']                = { link = "TSString" },
    ['@string.escape']         = { link = "TSStringEscape" },
    ['@string.regex']          = { link = "TSStringRegex" },
    ['@symbol']                = { link = "TSSymbol" },
    ['@tag']                   = { link = "TSTag" },
    ['@tag.delimiter']         = { link = "TSTagDelimiter" },
    ['@text']                  = { link = "TSText" },
    ['@strike']                = { link = "TSStrike" },
    ['@math']                  = { link = "TSMath" },
    ['@type']                  = { link = "TSType" },
    ['@type.builtin']          = { link = "TSTypeBuiltin" },
    ['@type.qualifier']        = { link = "TSKeyword" },
    ['@uri']                   = { link = "TSURI" },
    ['@variable']              = { link = "TSVariable" },
    ['@variable.builtin']      = { link = "TSVariableBuiltin" },
  }
end
