---@param theme OchaTheme
---@param _ OchaColors
return function(theme, _)
  vim.g.terminal_color_0  = theme.bg0[1]
  vim.g.terminal_color_8  = theme.bg1[1]
  vim.g.terminal_color_1  = theme.sakura[1]
  vim.g.terminal_color_9  = theme.sakura[1]
  vim.g.terminal_color_2 = theme.shinme[1]
  vim.g.terminal_color_10  = theme.shinme[1]
  vim.g.terminal_color_3 = theme.sakaeru[1]
  vim.g.terminal_color_11  = theme.taiyo[1]
  vim.g.terminal_color_4 = theme.sukai[1]
  vim.g.terminal_color_12  = theme.sukai[1]
  vim.g.terminal_color_5 = theme.seiun[1]
  vim.g.terminal_color_13  = theme.seiun[1]
  vim.g.terminal_color_6 = theme.ike[1]
  vim.g.terminal_color_14  = theme.ike[1]
  vim.g.terminal_color_7 = theme.bg3[1]
  vim.g.terminal_color_15  = theme.fg2[1]
end
