---@param theme evergarden.types.theme
---@param config evergarden.types.config
return function(theme, config)
  return {
    TSStrong    = { theme.none, theme.none, bold = true },
    TSEmphasis  = { theme.none, theme.none, italic = true },
    TSUnderline = { theme.none, theme.none, underline = true },
    TSNote      = { link = '@comment.note' },
    TSWarning   = { theme.diagnostic.warn },
    TSDanger    = { theme.diagnostic.warn },

    TSAnnotation         = { theme.seiun },
    TSAttribute          = { theme.seiun },
    TSBoolean            = { link = "Boolean" },
    TSCharacter          = { link = "Character" },
    TSComment            = { link = "Comment" },
    TSConditional        = { link = "Conditional" },
    TSConstBuiltin       = { link = "Constant" },
    TSConstMacro         = { link = "Constant" },
    TSConstant           = { link = "Constant" },
    TSConstructor        = { theme.shinme },
    TSException          = { link = "Exception" },
    TSField              = { theme.syntax.object },
    TSFloat              = { link = "Float" },
    TSFuncBuiltin        = { link = "Constant" },
    TSFuncMacro          = { theme.syntax.macro },
    TSFunction           = { link = "Function" },
    TSInclude            = { link = "Include" },
    TSKeyword            = { link = "Keyword" },
    TSKeywordFunction    = { link = "Keyword" },
    TSKeywordOperator    = { theme.taiyo },
    TSLabel              = { link = "Label" },
    TSMethod             = { theme.syntax.context },
    TSNamespace          = { link = "Constant" },
    TSNone               = { link = "Normal" },
    TSNumber             = { link = "Number" },
    TSOperator           = { link = "Operator" },
    TSParameter          = { link = "Identifier" },
    TSParameterReference = { link = "TSParameter" },
    TSProperty           = { theme.syntax.object },
    TSPunctBracket       = { theme.syntax.context },
    TSPunctDelimiter     = { link = "Delimiter" },
    TSPunctSpecial       = { link = "Special" },
    TSRepeat             = { link = "Repeat" },
    TSStorageClass       = { link = "StorageClass" },
    TSString             = { link = "String" },
    TSStringEscape       = { theme.sakaeru },
    TSStringRegex        = { theme.sakaeru },
    TSSymbol             = { theme.fg1 },
    TSTag                = { link = "Tag" },
    TSTagDelimiter       = { theme.fg1 },
    TSText               = { theme.fg1 },
    TSStrike             = { theme.fg2 },
    TSMath               = { theme.sukai },
    TSType               = { link = "Type" },
    TSTypeBuiltin        = { link = "Type" },
    TSURI                = { link = "markdownUrl" },
    TSVariable           = { link = "Identifier" },
    TSVariableBuiltin    = { link = "Constant" },
  }
end
